#ifndef ERRORCODE_H
#define ERRORCODE_H

#define ERROR_CODE_COUNT 21

enum ErrorCode{
	GLOBAL_ERROR,
	MEM_FAIL,
	NULL_PARAM,
	INVALID_ENUM_PARAM,
	INVALID_INT_PARAM,
	CONFLICTING_PARAM,
	PIECE_NOT_IN_BOARD,
	PIECE_MOVE_SAME_POS,
	PIECE_MOVE_OVERLAPS_ALLY,
	PIECE_MOVE_NOT_IN_RANGE,
	PIECE_MOVE_COLLISION,
	PIECE_MOVE_KING_CHECKED,
	PIECE_MOVE_ILLEGAL_CASTLE,
	PIECE_MOVE_UNEXPECTED_COLOR,
	BOARD_EMPTY_SQUARE,
	BOARD_NONEMPTY_SQUARE,
	BOARD_INVALID_EN_PASSANT_PIECE,
	DISPLAY_WIDTH_SMALL,
	DISPLAY_HEIGHT_SMALL,
	CAPTURE_MENU_BAD_INP,
	CAPTURE_MOVE_BAD_INP
};

#endif
